# Site settings
name: Yokee Chen
description: "懦怯囚禁人的灵魂，希望可以令你感受自由。强者自救，圣者渡人。"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  chendeqiang
facebook_username: chendeqiang
twitter_username: chendeqiang
weibo_username: Yoke-chen
blog_url: "/blog"
email: keshuixiansheng@126.com


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "imgs/jd.jpg"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
